"""
PoB Injector Updater - PowerShell-based updater for Windows
Generates and executes a PowerShell script to download and install updates
"""
import sys, os, time, subprocess

def generate_powershell_updater(repo, version, exe_dir, exe_path):
    """
    Generate PowerShell script that downloads, extracts, and installs update
    Returns path to generated script
    """
    script_path = os.path.join(exe_dir, "updater_temp.ps1")
    
    # GitHub release URL
    zip_url = f"https://github.com/{repo}/releases/download/v{version}/PoB_Injector_Release_v{version}.zip"
    
    # PowerShell script content
    ps_script = f"""# PoB Injector Auto-Updater
# Version: {version}
# Generated by updater.py

$ErrorActionPreference = "Stop"

Write-Host "============================================================"
Write-Host "PoB Injector Auto-Updater"
Write-Host "============================================================"
Write-Host "Target version: {version}"
Write-Host "Installation directory: {exe_dir}"
Write-Host ""

# Step 1: Download release ZIP
Write-Host "[Step 1/7] Downloading update..."
$zipPath = Join-Path $env:TEMP "pob_injector_update_{version}.zip"
$extractPath = Join-Path $env:TEMP "pob_injector_update_{version}_extracted"

try {{
    Invoke-WebRequest -Uri "{zip_url}" -OutFile $zipPath -UserAgent "PoB-Injector-Updater/2.0"
    $zipSize = (Get-Item $zipPath).Length / 1MB
    Write-Host "[OK] Downloaded: $([math]::Round($zipSize, 2)) MB"
}} catch {{
    Write-Host "[ERROR] Download failed: $_"
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

# Step 2: Extract ZIP
Write-Host ""
Write-Host "[Step 2/7] Extracting update..."
try {{
    if (Test-Path $extractPath) {{
        Remove-Item $extractPath -Recurse -Force
    }}
    Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
    Write-Host "[OK] Extracted to temp directory"
}} catch {{
    Write-Host "[ERROR] Extraction failed: $_"
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

# Step 3: Force close main process
Write-Host ""
Write-Host "[Step 3/7] Closing main process..."
$processName = "PoB-Injector"
try {{
    $procs = Get-Process -Name $processName -ErrorAction SilentlyContinue
    if ($procs) {{
        $procs | Stop-Process -Force
        Write-Host "[OK] Process terminated"
    }} else {{
        Write-Host "[OK] Process already stopped"
    }}
}} catch {{
    Write-Host "[WARNING] Could not stop process: $_"
}}

# Wait for Windows to release file locks
Write-Host "[INFO] Waiting for file locks to release..."
Start-Sleep -Seconds 3

# Step 4: Backup current exe
Write-Host ""
Write-Host "[Step 4/7] Backing up current installation..."
$exePath = "{exe_path}"
$backupPath = "$exePath.old"
try {{
    if (Test-Path $exePath) {{
        if (Test-Path $backupPath) {{
            Remove-Item $backupPath -Force
        }}
        Move-Item $exePath -Destination $backupPath -Force
        Write-Host "[OK] Backup created: PoB-Injector.exe.old"
    }} else {{
        Write-Host "[WARNING] Current exe not found, skipping backup"
    }}
}} catch {{
    Write-Host "[ERROR] Backup failed: $_"
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

# Step 5: Install update
Write-Host ""
Write-Host "[Step 5/7] Installing update..."
try {{
    $sourceDir = Join-Path $extractPath "PoB-Injector"
    Copy-Item "$sourceDir\\*" "{exe_dir}" -Recurse -Force
    Write-Host "[OK] Files updated"
}} catch {{
    Write-Host "[ERROR] Installation failed: $_"
    Write-Host "[INFO] Attempting rollback..."
    if (Test-Path $backupPath) {{
        Move-Item $backupPath -Destination $exePath -Force
        Write-Host "[OK] Rollback successful"
    }}
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

# Step 6: Verify new exe
Write-Host ""
Write-Host "[Step 6/7] Verifying installation..."
if (-not (Test-Path $exePath)) {{
    Write-Host "[ERROR] New exe not found after installation"
    if (Test-Path $backupPath) {{
        Write-Host "[INFO] Restoring from backup..."
        Move-Item $backupPath -Destination $exePath -Force
    }}
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

$newExeSize = (Get-Item $exePath).Length
if ($newExeSize -lt 1MB) {{
    Write-Host "[ERROR] New exe too small: $newExeSize bytes (possibly corrupted)"
    if (Test-Path $backupPath) {{
        Write-Host "[INFO] Restoring from backup..."
        Remove-Item $exePath -Force
        Move-Item $backupPath -Destination $exePath -Force
    }}
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

Write-Host "[OK] New exe verified: $([math]::Round($newExeSize / 1MB, 2)) MB"

# Step 7: Cleanup
Write-Host ""
Write-Host "[Step 7/7] Cleaning up..."
try {{
    Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
    Remove-Item $extractPath -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "[OK] Cleanup complete"
}} catch {{
    Write-Host "[WARNING] Cleanup failed: $_"
}}

Write-Host ""
Write-Host "============================================================"
Write-Host "Update completed successfully!"
Write-Host "============================================================"
Write-Host "Restarting application in 2 seconds..."
Start-Sleep -Seconds 2

# Restart application
try {{
    Start-Process -FilePath "{exe_path}" -ArgumentList "--updated" -WorkingDirectory "{exe_dir}"
    Write-Host "[OK] Application restarted"
}} catch {{
    Write-Host "[ERROR] Failed to restart: $_"
    Write-Host "[INFO] Please start the application manually"
    Write-Host ""
    Write-Host "Press any key to exit..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    exit 1
}}

# Self-destruct this script
Start-Sleep -Seconds 1
Remove-Item "{script_path}" -Force -ErrorAction SilentlyContinue
"""
    
    # Write script to file
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(ps_script)
    
    return script_path

def main():
    print("============================================================")
    print("PoB Injector Updater (PowerShell-based)")
    print("============================================================")
    
    # Check if running in frozen/compiled mode
    is_compiled = getattr(sys, 'frozen', False)
    
    if is_compiled:
        exe_path = sys.executable
        exe_dir = os.path.dirname(exe_path)
    else:
        # Dev mode - not supported with PowerShell updater
        print("[ERROR] PowerShell updater only works in compiled mode")
        print("[INFO] In dev mode, use git pull instead")
        return
    
    print(f"Mode: Compiled")
    print(f"Exe: {exe_path}")
    print(f"Dir: {exe_dir}")
    print("")
    
    # Parse arguments
    if len(sys.argv) < 3:
        print("[ERROR] Usage: updater.py <repo> <version>")
        print("Example: updater.py rauldzmartin/PoB-Injector 0.6.43-beta")
        return
    
    repo = sys.argv[1]
    version = sys.argv[2]
    
    print(f"Repository: {repo}")
    print(f"Version: {version}")
    print("")
    
    # Wait for server to shut down
    print("Waiting for server to shut down...")
    time.sleep(2)
    
    # Generate PowerShell script
    print("Generating PowerShell updater script...")
    script_path = generate_powershell_updater(repo, version, exe_dir, exe_path)
    print(f"[OK] Script generated: {script_path}")
    print("")
    
    # Execute PowerShell script
    print("Launching PowerShell updater...")
    print("============================================================")
    print("")
    
    try:
        # Execute PowerShell script in a new window so user can see progress
        subprocess.Popen([
            'powershell.exe',
            '-ExecutionPolicy', 'Bypass',
            '-NoProfile',
            '-File', script_path
        ], creationflags=subprocess.CREATE_NEW_CONSOLE)
        
        print("[OK] PowerShell updater launched")
        print("[INFO] This process will now exit")
        
    except Exception as e:
        print(f"[ERROR] Failed to launch PowerShell: {e}")
        print("")
        print("Trying to clean up...")
        try:
            os.remove(script_path)
        except:
            pass

if __name__ == "__main__":
    main()
